#!/bin/sh
exec 2>&1

mkdir -p /persist/comma
chown comma:comma /persist/comma

if [ ! -s /persist/comma/id_ed25519 ]; then
  openssl genpkey -algorithm Ed25519 -out /persist/comma/id_ed25519
  openssl pkey -in /persist/comma/id_ed25519 -pubout -out /persist/comma/id_ed25519.pub
  chmod 600 /persist/comma/id_ed25519
  chmod 644 /persist/comma/id_ed25519.pub
  chown comma:comma /persist/comma/id_ed25519 /persist/comma/id_ed25519.pub
fi

touch /run/runit/service/keygen/down
