#!/usr/bin/env python3
from __future__ import annotations

import argparse
import contextlib
import fcntl
import hashlib
import json
import lzma
import os
import re
import struct
import subprocess
import sys
import tempfile
import time
import urllib.parse
import urllib.error
import urllib.request
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import BinaryIO, Callable, Iterator, Sequence


UPDATER_VERSION = 1
MANIFEST_VERSION = 1
PRODUCT = "asius-v1"
LEGACY_PRODUCTS = {"radxa-dragon-q6a"}


def _supported_system_disk(path: Path) -> bool:
  # Qualcomm UFS is exposed through the SCSI disk layer; NVMe uses its native
  # block naming.  v1 deliberately has no SD/eMMC update target.
  return re.fullmatch(r"(?:nvme\d+n\d+|sd[a-z]+)", path.name) is not None

def _system_disk() -> Path:
  override = os.environ.get("VAMOS_DISK")
  if override:
    return Path(override)

  sources: list[str] = []
  mounted_root = subprocess.run(
    ["findmnt", "-n", "-o", "SOURCE", "/"],
    check=False,
    text=True,
    stdout=subprocess.PIPE,
    stderr=subprocess.DEVNULL,
  ).stdout.strip()
  if mounted_root:
    sources.append(mounted_root)
  for label in ("rootfs_a", "rootfs_b", "rootfs"):
    candidate = Path("/dev/disk/by-partlabel") / label
    if candidate.exists():
      sources.append(str(candidate.resolve()))

  for source in sources:
    parent = subprocess.run(
      ["lsblk", "-n", "-o", "PKNAME", source],
      check=False,
      text=True,
      stdout=subprocess.PIPE,
      stderr=subprocess.DEVNULL,
    ).stdout.strip().splitlines()
    if parent and parent[0]:
      candidate = Path("/dev") / parent[0]
      if _supported_system_disk(candidate):
        return candidate

  for candidate in (Path("/dev/nvme0n1"), Path("/dev/sda")):
    if candidate.exists():
      return candidate
  return Path("/dev/nvme0n1")


DISK = _system_disk()
PARTLABEL_DIR = Path("/dev/disk/by-partlabel")
STATE_DIR = Path("/data/vamos-update")
STATE_FILE = STATE_DIR / "state.json"
HISTORY_FILE = STATE_DIR / "history.jsonl"
USERDATA_MARKER = Path("/data/.vamos-userdata")
LAYOUT_READY_MARKER = Path("/data/.vamos-ab-ready")
LOCK_FILE = Path("/run/lock/vamos-update.lock")
CMDLINE_FILE = Path("/proc/cmdline")
TRIAL_MARKER = Path("/run/vamos-trial-boot")
HEALTHY_MARKER = Path("/run/vamos-boot-healthy")
STAGE1_MARKER = Path("/run/vamos-stage1-ready")
WATCHDOG_PID_FILE = Path("/run/vamos-watchdog.pid")
WATCHDOG_LOG = Path("/run/vamos-watchdog.log")
WATCHDOG_DEVICE = Path("/dev/watchdog0")
WATCHDOG_READY_MARKER = Path("/run/vamos-watchdog-ready")
WATCHDOG_DISARMED_MARKER = Path("/run/vamos-watchdog-disarmed")
UPDATE_PUBLIC_KEY = Path("/usr/share/vamos/update-public.pem")
EXPAND_BACKUP = Path("/run/vamos-partition-table-before-expand.sfdisk")

ESP_SIZE = 256 * 1024 * 1024
SYSTEM_SIZE = 10 * 1024 * 1024 * 1024
IO_CHUNK_SIZE = 4 * 1024 * 1024
MAX_MANIFEST_SIZE = 1024 * 1024
ED25519_SIGNATURE_SIZE = 64
BOOT_SELECTOR_SOURCE = Path("/usr/share/vamos/BOOTAA64.EFI")
ESP_PRIMARY_LOADER = Path("Image")
ESP_RECOVERY_LOADER = Path("EFI/BOOT/BOOTAA64.EFI")
ESP_KERNEL = Path("EFI/vamos/Image")
BOOT_CONTROL = Path("EFI/vamos/grubenv")
ESP_VOLUME_LABEL = {"a": "VAMOS-A", "b": "VAMOS-B"}
ROOT_LABEL = {"a": "rootfs_a", "b": "rootfs_b"}
ESP_LABEL = {"a": "esp_a", "b": "esp_b"}
PARTITION_NUMBER = {
  ("a", "esp"): 1,
  ("a", "system"): 2,
  ("b", "esp"): 3,
  ("b", "system"): 4,
}
PARTITION_LABEL = {
  (slot, image_name): ESP_LABEL[slot] if image_name == "esp" else ROOT_LABEL[slot]
  for slot, image_name in PARTITION_NUMBER
}
GRUB_ENV_SIZE = 1024
GRUB_ENV_HEADER = (
  b"# GRUB Environment Block\n"
  b"# WARNING: Do not edit this file by tools other than grub-editenv!!!\n"
)
BOOT_PHASE_RANK = {"armed": 1, "attempted": 2, "stable": 3}


class UpdateError(RuntimeError):
  pass


@dataclass(frozen=True)
class ImageSpec:
  name: str
  source: str
  size: int
  sha256: str
  compression: str


@dataclass(frozen=True)
class Manifest:
  version: str
  images: tuple[ImageSpec, ...]
  source: str


def log(message: str) -> None:
  print(f"vamos-update: {message}", flush=True)


def run(command: Sequence[str], *, check: bool = True, capture: bool = True) -> subprocess.CompletedProcess[str]:
  return subprocess.run(
    list(command),
    check=check,
    text=True,
    stdout=subprocess.PIPE if capture else None,
    stderr=subprocess.STDOUT if capture else None,
  )


def disk_partition(number: int, disk: Path | None = None) -> Path:
  target = DISK if disk is None else disk
  if not _supported_system_disk(target):
    raise UpdateError(f"unsupported system disk {target}; vamOS v1 supports only NVMe and UFS")
  separator = "p" if target.name[-1:].isdigit() else ""
  return Path(f"{target}{separator}{number}")


def atomic_write_json(path: Path, value: object) -> None:
  path.parent.mkdir(parents=True, exist_ok=True)
  fd, temporary = tempfile.mkstemp(prefix=f".{path.name}.", dir=path.parent)
  try:
    with os.fdopen(fd, "w", encoding="utf-8") as output:
      os.fchmod(output.fileno(), 0o644)
      json.dump(value, output, indent=2, sort_keys=True)
      output.write("\n")
      output.flush()
      os.fsync(output.fileno())
    os.replace(temporary, path)
    directory_fd = os.open(path.parent, os.O_RDONLY | os.O_DIRECTORY)
    try:
      os.fsync(directory_fd)
    finally:
      os.close(directory_fd)
  finally:
    with contextlib.suppress(FileNotFoundError):
      os.unlink(temporary)


def load_state() -> dict:
  try:
    with STATE_FILE.open(encoding="utf-8") as state_file:
      value = json.load(state_file)
    return value if isinstance(value, dict) else {}
  except (FileNotFoundError, json.JSONDecodeError):
    return {}


def save_state(state: dict, event: str | None = None) -> None:
  state = dict(state)
  state["updated_at"] = int(time.time())
  atomic_write_json(STATE_FILE, state)
  if event is not None:
    record = dict(state)
    record["event"] = event
    with HISTORY_FILE.open("a", encoding="utf-8") as history:
      history.write(json.dumps(record, sort_keys=True) + "\n")
      history.flush()
      os.fsync(history.fileno())


@contextlib.contextmanager
def update_lock() -> Iterator[None]:
  LOCK_FILE.parent.mkdir(parents=True, exist_ok=True)
  with LOCK_FILE.open("w") as lock:
    try:
      fcntl.flock(lock, fcntl.LOCK_EX | fcntl.LOCK_NB)
    except BlockingIOError as exc:
      raise UpdateError("another vamOS update operation is already running") from exc
    yield


def sha256_file(path: Path, size: int | None = None, progress_callback: Callable[[int], None] | None = None) -> str:
  digest = hashlib.sha256()
  remaining = size
  read = 0
  last_progress = -1
  with path.open("rb", buffering=0) as source:
    while remaining is None or remaining > 0:
      read_size = IO_CHUNK_SIZE if remaining is None else min(IO_CHUNK_SIZE, remaining)
      chunk = source.read(read_size)
      if not chunk:
        break
      digest.update(chunk)
      read += len(chunk)
      if remaining is not None:
        remaining -= len(chunk)
      if progress_callback is not None and size is not None and size > 0:
        progress = int(read * 100 / size)
        if progress >= last_progress + 5 or progress == 100:
          progress_callback(progress)
          last_progress = progress
  if remaining not in (None, 0):
    raise UpdateError(f"{path} is shorter than the expected {size} bytes")
  return digest.hexdigest()


def _read_url_bytes(source: str, maximum_size: int) -> bytes:
  request = urllib.request.Request(source, headers={"Accept-Encoding": "identity", "User-Agent": "vamos-update/1"})
  with urllib.request.urlopen(request, timeout=60) as response:
    payload = response.read(maximum_size + 1)
  if len(payload) > maximum_size:
    raise UpdateError(f"{source} exceeds the {maximum_size}-byte size limit")
  return payload


def verify_manifest_signature(payload: bytes, signature: bytes) -> None:
  if len(signature) != ED25519_SIGNATURE_SIZE:
    raise UpdateError("update manifest has an invalid Ed25519 signature size")
  if not UPDATE_PUBLIC_KEY.is_file():
    raise UpdateError(f"update signing key is missing: {UPDATE_PUBLIC_KEY}")

  with tempfile.TemporaryDirectory(prefix="vamos-signature-") as temporary:
    manifest_path = Path(temporary) / "manifest"
    signature_path = Path(temporary) / "signature"
    manifest_path.write_bytes(payload)
    signature_path.write_bytes(signature)
    result = run([
      "openssl", "pkeyutl", "-verify", "-pubin", "-inkey", str(UPDATE_PUBLIC_KEY),
      "-rawin", "-in", str(manifest_path), "-sigfile", str(signature_path),
    ], check=False)
  if result.returncode != 0:
    raise UpdateError("update manifest signature verification failed")


def _read_json_source(source: str) -> tuple[object, str]:
  parsed = urllib.parse.urlparse(source)
  if parsed.scheme in ("http", "https"):
    payload = _read_url_bytes(source, MAX_MANIFEST_SIZE)
    signature = _read_url_bytes(source + ".sig", ED25519_SIGNATURE_SIZE)
    verify_manifest_signature(payload, signature)
    return json.loads(payload), source

  path = Path(parsed.path if parsed.scheme == "file" else source).expanduser().resolve()
  payload = path.read_bytes()
  if len(payload) > MAX_MANIFEST_SIZE:
    raise UpdateError(f"{path} exceeds the {MAX_MANIFEST_SIZE}-byte size limit")
  signature_path = Path(str(path) + ".sig")
  if signature_path.is_file():
    verify_manifest_signature(payload, signature_path.read_bytes())
  return json.loads(payload), path.as_uri()


def _resolve_source(base: str, value: str) -> str:
  parsed = urllib.parse.urlparse(value)
  if parsed.scheme:
    return value
  return urllib.parse.urljoin(base, value)


def _parse_image(raw: object, base: str) -> ImageSpec:
  if not isinstance(raw, dict):
    raise UpdateError("manifest partition entries must be JSON objects")
  try:
    name = str(raw["name"])
    source = str(raw.get("url") or raw.get("path"))
    size = int(raw["size"])
    sha256 = str(raw.get("sha256") or raw.get("hash_raw") or raw["hash"]).lower()
  except (KeyError, TypeError, ValueError) as exc:
    raise UpdateError(f"invalid manifest partition: {raw!r}") from exc

  compression = str(raw.get("compression", "xz" if source.endswith(".xz") else "none")).lower()
  if name not in ("esp", "system"):
    raise UpdateError(f"unsupported partition name {name!r}")
  if size != {"esp": ESP_SIZE, "system": SYSTEM_SIZE}[name]:
    raise UpdateError(f"{name} image has unsafe size {size}")
  if not re.fullmatch(r"[0-9a-f]{64}", sha256):
    raise UpdateError(f"{name} image has an invalid SHA-256")
  if compression not in ("none", "xz"):
    raise UpdateError(f"{name} image has unsupported compression {compression!r}")
  if not source or source == "None":
    raise UpdateError(f"{name} image has no source")
  return ImageSpec(name, _resolve_source(base, source), size, sha256, compression)


def load_manifest(source: str) -> Manifest:
  raw, base = _read_json_source(source)
  if isinstance(raw, list):
    # Accept comma-style manifests for local tooling compatibility.
    partitions = raw
    version = "unspecified"
    manifest_version = 1
    product = PRODUCT
  elif isinstance(raw, dict):
    partitions = raw.get("partitions")
    version = str(raw.get("version", "unspecified"))
    manifest_version = raw.get("manifest_version")
    product = raw.get("product")
    minimum_updater = int(raw.get("minimum_updater_version", 1))
    if minimum_updater > UPDATER_VERSION:
      raise UpdateError(f"manifest requires updater version {minimum_updater}")
  else:
    raise UpdateError("manifest must be an object or a comma-style partition list")

  if manifest_version != MANIFEST_VERSION:
    raise UpdateError(f"unsupported manifest version {manifest_version!r}")
  if product != PRODUCT and product not in LEGACY_PRODUCTS:
    raise UpdateError(f"manifest is for {product!r}, expected {PRODUCT!r}")
  if not isinstance(partitions, list):
    raise UpdateError("manifest has no partitions list")

  images = tuple(_parse_image(partition, base) for partition in partitions)
  names = [image.name for image in images]
  if sorted(names) != ["esp", "system"] or len(names) != len(set(names)):
    raise UpdateError("manifest must contain exactly one esp and one system image")
  return Manifest(version, images, source)


@contextlib.contextmanager
def open_image(spec: ImageSpec) -> Iterator[BinaryIO]:
  parsed = urllib.parse.urlparse(spec.source)
  raw: BinaryIO
  response = None
  if parsed.scheme in ("http", "https"):
    request = urllib.request.Request(spec.source, headers={"Accept-Encoding": "identity", "User-Agent": "vamos-update/1"})
    response = urllib.request.urlopen(request, timeout=60)
    raw = response
  elif parsed.scheme == "file":
    raw = open(urllib.request.url2pathname(parsed.path), "rb", buffering=0)
  elif not parsed.scheme:
    raw = open(spec.source, "rb", buffering=0)
  else:
    raise UpdateError(f"unsupported image URL scheme {parsed.scheme!r}")

  try:
    if spec.compression == "xz":
      with lzma.LZMAFile(raw, "rb") as decompressed:
        yield decompressed
    else:
      yield raw
  finally:
    if response is not None:
      response.close()
    else:
      raw.close()


def inspect_local_image(path: Path, name: str) -> ImageSpec:
  compression = "xz" if path.name.endswith(".xz") else "none"
  temporary = ImageSpec(name, path.resolve().as_uri(), {"esp": ESP_SIZE, "system": SYSTEM_SIZE}[name], "0" * 64, compression)
  digest = hashlib.sha256()
  size = 0
  with open_image(temporary) as source:
    while chunk := source.read(IO_CHUNK_SIZE):
      size += len(chunk)
      if size > temporary.size:
        raise UpdateError(f"{path} expands beyond {temporary.size} bytes")
      digest.update(chunk)
  if size != temporary.size:
    raise UpdateError(f"{path} expands to {size} bytes, expected {temporary.size}")
  return ImageSpec(name, temporary.source, size, digest.hexdigest(), compression)


def manifest_from_directory(directory: Path) -> Manifest:
  directory = directory.expanduser().resolve()
  images: list[ImageSpec] = []
  for name in ("esp", "system"):
    candidates = [directory / f"{name}.img.xz", directory / f"{name}.img"]
    path = next((candidate for candidate in candidates if candidate.is_file()), None)
    if path is None:
      raise UpdateError(f"{directory} has no {name}.img or {name}.img.xz")
    log(f"hashing local {path.name}")
    images.append(inspect_local_image(path, name))

  version = f"local-{int(time.time())}"
  version_file = directory / "VERSION"
  if version_file.is_file():
    version = version_file.read_text(encoding="utf-8").strip()
  return Manifest(version, tuple(images), directory.as_uri() + "/")


def cmdline() -> str:
  return CMDLINE_FILE.read_text(encoding="utf-8").strip()


def current_slot() -> str:
  match = re.search(r"(?:^|\s)vamos\.slot=([ab])(?:\s|$)", cmdline())
  if match:
    return match.group(1)

  root = Path(run(["findmnt", "-n", "-o", "SOURCE", "/"]).stdout.strip()).resolve()
  for slot, number in (("a", 2), ("b", 4)):
    if root == disk_partition(number).resolve():
      return slot
  raise UpdateError("cannot determine active vamOS slot")


def partition_path(slot: str, image_name: str) -> Path:
  try:
    number = PARTITION_NUMBER[(slot, image_name)]
  except KeyError as exc:
    raise UpdateError(f"invalid slot or image name: {slot}/{image_name}") from exc
  path = disk_partition(number)
  if not path.exists():
    label = PARTITION_LABEL[(slot, image_name)]
    raise UpdateError(f"required partition {label} does not exist on system disk {DISK}")
  return path


def block_size(path: Path) -> int:
  return int(run(["blockdev", "--getsize64", str(path)]).stdout.strip())


def partition_label(path: Path) -> str:
  return run(["blkid", "-s", "PARTLABEL", "-o", "value", str(path)]).stdout.strip()


def write_image(spec: ImageSpec, destination: Path,
                progress_callback: Callable[[str, int], None] | None = None) -> None:
  actual_size = block_size(destination)
  if actual_size < spec.size:
    raise UpdateError(f"{destination} is {actual_size} bytes, smaller than {spec.size}")

  digest = hashlib.sha256()
  written = 0
  last_progress = -1
  log(f"writing {spec.name} to {destination}")
  with open_image(spec) as source, destination.open("r+b", buffering=0) as output:
    while chunk := source.read(IO_CHUNK_SIZE):
      written += len(chunk)
      if written > spec.size:
        raise UpdateError(f"{spec.name} expands beyond declared size")
      output.write(chunk)
      digest.update(chunk)
      progress = int(written * 100 / spec.size)
      if progress >= last_progress + 5:
        log(f"{spec.name}: {progress}%")
        if progress_callback is not None:
          progress_callback("writing", progress)
        last_progress = progress
    output.flush()
    os.fsync(output.fileno())

  if written != spec.size:
    raise UpdateError(f"{spec.name} wrote {written} bytes, expected {spec.size}")
  if digest.hexdigest() != spec.sha256:
    raise UpdateError(f"{spec.name} source SHA-256 mismatch")

  log(f"verifying {spec.name} from disk")
  actual_hash = sha256_file(
    destination,
    spec.size,
    None if progress_callback is None else lambda progress: progress_callback("verifying", progress),
  )
  if actual_hash != spec.sha256:
    raise UpdateError(f"{spec.name} on-device SHA-256 mismatch")


@contextlib.contextmanager
def mounted_read_only(device: Path) -> Iterator[Path]:
  with tempfile.TemporaryDirectory(prefix="vamos-verify-") as mount_dir:
    mount_path = Path(mount_dir)
    run(["mount", "-o", "ro,noload", str(device), str(mount_path)])
    try:
      yield mount_path
    finally:
      run(["umount", str(mount_path)], capture=False)


def verify_system_contents(device: Path, expected_version: str) -> None:
  check = run(["e2fsck", "-fn", str(device)], check=False)
  if check.returncode != 0:
    raise UpdateError(f"system image filesystem check failed:\n{check.stdout.strip()}")
  with mounted_read_only(device) as root:
    required = (
      root / "ASIUS",
      root / "VERSION",
      root / "etc/runit/1",
      root / "usr/comma/comma.sh",
      root / "usr/bin/vamos-update",
      root / "usr/bin/vamos-boot",
      root / "usr/lib/vamos/update.py",
      root / "usr/share/vamos/BOOTAA64.EFI",
      root / "usr/share/vamos/update-public.pem",
    )
    missing = [str(path.relative_to(root)) for path in required if not path.exists()]
    if missing:
      raise UpdateError(f"system image lacks rollback support: {', '.join(missing)}")
    if not os.access(root / "etc/runit/1", os.X_OK):
      raise UpdateError("system image runit stage 1 is not executable")
    if not os.access(root / "usr/comma/comma.sh", os.X_OK):
      raise UpdateError("system image launcher is not executable")
    actual_version = (root / "VERSION").read_text(encoding="utf-8").strip()
    if expected_version not in ("", "unspecified") and actual_version != expected_version:
      raise UpdateError(f"system image version {actual_version!r} does not match manifest {expected_version!r}")


def verify_esp_contents(device: Path) -> None:
  check = run(["fsck.vfat", "-n", str(device)], check=False)
  if check.returncode != 0:
    raise UpdateError(f"ESP filesystem check failed:\n{check.stdout.strip()}")
  with tempfile.TemporaryDirectory(prefix="vamos-esp-") as mount_dir:
    mount_path = Path(mount_dir)
    run(["mount", "-o", "ro", str(device), str(mount_path)])
    try:
      required = (
        mount_path / ESP_RECOVERY_LOADER,
        mount_path / ESP_PRIMARY_LOADER,
        mount_path / ESP_KERNEL,
        mount_path / BOOT_CONTROL,
        mount_path / "qcs6490-radxa-dragon-q6a.dtb",
      )
      missing = [str(path.relative_to(mount_path)) for path in required if not path.is_file()]
      if missing:
        raise UpdateError(f"ESP image is not bootable: {', '.join(missing)}")
      verify_arm64_efi(required[0])
      verify_arm64_efi(required[1])
      verify_arm64_efi(required[2])
      if required[0].read_bytes() != required[1].read_bytes():
        raise UpdateError("ESP selector copies do not match")
      decode_boot_control(required[3].read_bytes())
      if required[4].read_bytes()[:4] != b"\xd0\r\xfe\xed":
        raise UpdateError("ESP device tree has an invalid FDT header")
    finally:
      run(["umount", str(mount_path)], capture=False)


def verify_arm64_efi(path: Path) -> None:
  with path.open("rb") as image:
    header = image.read(4096)
  if len(header) < 64 or header[:2] != b"MZ":
    raise UpdateError("ESP kernel has no EFI MZ header")
  pe_offset = struct.unpack_from("<I", header, 0x3c)[0]
  if pe_offset + 6 > len(header) or header[pe_offset:pe_offset + 4] != b"PE\0\0":
    raise UpdateError("ESP kernel has no PE header")
  machine = struct.unpack_from("<H", header, pe_offset + 4)[0]
  if machine != 0xaa64:
    raise UpdateError(f"ESP kernel is for unsupported PE machine 0x{machine:04x}")


def encode_boot_control(values: dict[str, str | int]) -> bytes:
  ordered = ("generation", "active", "pending", "phase", "root_a", "root_b", "edl_request")
  lines = []
  for key in ordered:
    value = str(values.get(key, 0 if key == "edl_request" else ""))
    if "\n" in value or "\r" in value or "=" in key:
      raise UpdateError(f"invalid boot-control value for {key}")
    lines.append(f"{key}={value}\n".encode())
  payload = GRUB_ENV_HEADER + b"".join(lines)
  if len(payload) > GRUB_ENV_SIZE:
    raise UpdateError("boot-control environment exceeds the GRUB block size")
  encoded = payload + b"#" * (GRUB_ENV_SIZE - len(payload))
  decode_boot_control(encoded)
  return encoded


def decode_boot_control(payload: bytes) -> dict[str, str | int]:
  if len(payload) != GRUB_ENV_SIZE or not payload.startswith(GRUB_ENV_HEADER):
    raise UpdateError("invalid GRUB boot-control block")
  body = payload[len(GRUB_ENV_HEADER):].rstrip(b"#")
  # Early U-Boot prototypes padded the block after snprintf() without
  # replacing its terminating NUL. Accept that one exact legacy form so a
  # deployed device can rewrite both copies canonically on its next update.
  if body.endswith(b"\0"):
    body = body[:-1]
  values: dict[str, str] = {}
  for raw_line in body.splitlines():
    try:
      key, separator, value = raw_line.decode("ascii").partition("=")
    except UnicodeDecodeError as exc:
      raise UpdateError("non-ASCII GRUB boot-control block") from exc
    if not separator or key in values:
      raise UpdateError("malformed GRUB boot-control block")
    values[key] = value
  try:
    generation = int(values["generation"])
  except (KeyError, ValueError) as exc:
    raise UpdateError("boot-control generation is invalid") from exc
  active = values.get("active")
  pending = values.get("pending", "")
  phase = values.get("phase")
  edl_request = values.get("edl_request", "0")
  if generation < 0 or active not in ("a", "b") or phase not in BOOT_PHASE_RANK:
    raise UpdateError("boot-control state is invalid")
  if edl_request not in ("0", "1"):
    raise UpdateError("boot-control EDL request is invalid")
  if phase != "stable" and (pending not in ("a", "b") or pending == active):
    raise UpdateError("boot-control trial target is invalid")
  for slot in ("a", "b"):
    root = values.get(f"root_{slot}", "")
    if not re.fullmatch(r"PART(?:UUID|LABEL)=[A-Za-z0-9._-]+", root):
      raise UpdateError(f"boot-control root for slot {slot} is invalid")
  return {**values, "generation": generation, "edl_request": int(edl_request)}


@contextlib.contextmanager
def mounted_esp(device: Path, *, read_only: bool) -> Iterator[Path]:
  with tempfile.TemporaryDirectory(prefix="vamos-esp-") as mount_dir:
    mount_path = Path(mount_dir)
    run(["mount", "-o", "ro" if read_only else "rw", str(device), str(mount_path)])
    try:
      yield mount_path
    finally:
      run(["umount", str(mount_path)], capture=False)


def _atomic_write_bytes(path: Path, payload: bytes) -> None:
  path.parent.mkdir(parents=True, exist_ok=True)
  temporary = path.with_name(f".{path.name}.new")
  with temporary.open("wb") as output:
    output.write(payload)
    output.flush()
    os.fsync(output.fileno())
  os.replace(temporary, path)
  directory_fd = os.open(path.parent, os.O_RDONLY | os.O_DIRECTORY)
  try:
    os.fsync(directory_fd)
  finally:
    os.close(directory_fd)


def read_boot_controls() -> list[dict[str, str | int]]:
  controls = []
  for slot in ("a", "b"):
    try:
      with mounted_esp(partition_path(slot, "esp"), read_only=True) as esp:
        control = decode_boot_control((esp / BOOT_CONTROL).read_bytes())
        control["source_slot"] = slot
        controls.append(control)
    except (UpdateError, OSError, subprocess.SubprocessError):
      continue
  return controls


def selected_boot_control() -> dict[str, str | int] | None:
  controls = read_boot_controls()
  if not controls:
    return None
  return max(controls, key=lambda control: (
    int(control["generation"]), BOOT_PHASE_RANK[str(control["phase"])],
  ))


def root_reference(slot: str) -> str:
  try:
    partuuid = run(["blkid", "-s", "PARTUUID", "-o", "value", str(partition_path(slot, "system"))]).stdout.strip()
  except Exception:
    partuuid = ""
  return f"PARTUUID={partuuid}" if re.fullmatch(r"[A-Fa-f0-9-]+", partuuid) else f"PARTLABEL={ROOT_LABEL[slot]}"


def _write_control_to_slot(slot: str, payload: bytes) -> bool:
  try:
    device = partition_path(slot, "esp")
    with mounted_esp(device, read_only=False) as esp:
      if not (esp / ESP_PRIMARY_LOADER).is_file() or not (esp / ESP_KERNEL).is_file():
        return False
      _atomic_write_bytes(esp / BOOT_CONTROL, payload)
    return True
  except (UpdateError, OSError, subprocess.SubprocessError):
    return False


def set_boot_control(active: str, pending: str = "", phase: str = "stable") -> int:
  if active not in ("a", "b") or phase not in BOOT_PHASE_RANK:
    raise UpdateError("refusing invalid boot-control state")
  if phase != "stable" and (pending not in ("a", "b") or pending == active):
    raise UpdateError("refusing invalid boot-control trial")
  previous = selected_boot_control()
  generation = (int(previous["generation"]) if previous is not None else 0) + 1
  values: dict[str, str | int] = {
    "generation": generation,
    "active": active,
    "pending": pending,
    "phase": phase,
    "root_a": root_reference("a"),
    "root_b": root_reference("b"),
  }
  payload = encode_boot_control(values)
  written = [_write_control_to_slot(slot, payload) for slot in ("a", "b")]
  if not any(written):
    raise UpdateError("no bootable ESP accepted the boot-control state")
  return generation


def request_edl(*, reboot: bool = True) -> int:
  if os.geteuid() != 0:
    raise UpdateError("software EDL requires root privileges")
  previous = selected_boot_control()
  if previous is None:
    raise UpdateError("no valid redundant boot-control state found")

  values: dict[str, str | int] = {
    "generation": int(previous["generation"]) + 1,
    "active": str(previous["active"]),
    "pending": str(previous.get("pending", "")),
    "phase": str(previous["phase"]),
    "root_a": str(previous["root_a"]),
    "root_b": str(previous["root_b"]),
    "edl_request": 1,
  }
  payload = encode_boot_control(values)
  written = [_write_control_to_slot(slot, payload) for slot in ("a", "b")]
  if not any(written):
    raise UpdateError("no bootable ESP accepted the software EDL request")
  os.sync()
  if reboot:
    run(["reboot", "-f"], capture=False)
  return int(values["generation"])


def _install_selector_on_slot(slot: str, selector: bytes, control: bytes, *, device: Path | None = None) -> None:
  device = device or partition_path(slot, "esp")
  run(["fatlabel", str(device), ESP_VOLUME_LABEL[slot]], capture=False)
  with mounted_esp(device, read_only=False) as esp:
    primary = esp / ESP_PRIMARY_LOADER
    recovery = esp / ESP_RECOVERY_LOADER
    kernel = esp / ESP_KERNEL
    primary.parent.mkdir(parents=True, exist_ok=True)
    recovery.parent.mkdir(parents=True, exist_ok=True)
    kernel.parent.mkdir(parents=True, exist_ok=True)

    current = primary.read_bytes() if primary.is_file() else b""
    if not kernel.is_file():
      if not current or current == selector:
        raise UpdateError(f"slot {slot} has no recoverable kernel")
      _atomic_write_bytes(kernel, current)
    verify_arm64_efi(kernel)

    # The state and preserved kernel land before the board entry at /Image is
    # replaced, so loss of power at any earlier point still boots the old path.
    _atomic_write_bytes(esp / BOOT_CONTROL, control)
    _atomic_write_bytes(recovery, selector)
    verify_arm64_efi(recovery)
    _atomic_write_bytes(primary, selector)
    verify_arm64_efi(primary)
  os.sync()


def prepare_disk_selector(active: str, target: str) -> int:
  target_device = partition_path(target, "esp")
  run(["fatlabel", str(target_device), ESP_VOLUME_LABEL[target]], capture=False)
  with mounted_esp(target_device, read_only=True) as target_esp:
    selector = (target_esp / ESP_PRIMARY_LOADER).read_bytes()
    verify_arm64_efi(target_esp / ESP_PRIMARY_LOADER)
    verify_arm64_efi(target_esp / ESP_KERNEL)

  previous = selected_boot_control()
  generation = (int(previous["generation"]) if previous is not None else 0) + 1
  control = encode_boot_control({
    "generation": generation,
    "active": active,
    "pending": "",
    "phase": "stable",
    "root_a": root_reference("a"),
    "root_b": root_reference("b"),
  })
  _install_selector_on_slot(active, selector, control)
  if not _write_control_to_slot(target, control):
    raise UpdateError(f"failed to initialize boot control on slot {target}")
  return generation


def prepare_trial_boot(current: str, target: str) -> int:
  return set_boot_control(current, target, "armed")


def commit_boot(current: str, previous: str) -> int:
  del previous
  return set_boot_control(current)


def rollback_boot(current: str, failed: str) -> int:
  del failed
  return set_boot_control(current)


def verify_layout() -> None:
  for slot in ("a", "b"):
    for image_name, expected_size in (("esp", ESP_SIZE), ("system", SYSTEM_SIZE)):
      path = partition_path(slot, image_name)
      expected_label = PARTITION_LABEL[(slot, image_name)]
      actual_label = partition_label(path)
      if actual_label != expected_label:
        raise UpdateError(f"{path} has PARTLABEL {actual_label!r}, expected {expected_label!r}")
      if block_size(path) != expected_size:
        raise UpdateError(f"{path} is not exactly {expected_size} bytes")
  userdata = disk_partition(5)
  if not userdata.exists():
    raise UpdateError(f"userdata partition does not exist on system disk {DISK}")
  actual_label = partition_label(userdata)
  if actual_label != "userdata":
    raise UpdateError(f"{userdata} has PARTLABEL {actual_label!r}, expected 'userdata'")
  if not os.path.ismount("/data"):
    raise UpdateError("/data is not mounted from persistent userdata")
  data_source = run(["findmnt", "-n", "-o", "SOURCE", "/data"]).stdout.strip()
  if not data_source or Path(data_source).resolve() != userdata.resolve():
    raise UpdateError(f"/data is mounted from {data_source or 'an unknown source'}, expected {userdata}")


def activate_staged(*, reboot: bool = False) -> dict:
  if os.geteuid() != 0:
    raise UpdateError("activation must run as root")
  verify_layout()
  state = load_state()
  active = current_slot()
  target = state.get("target_slot")
  if state.get("state") not in ("verified", "ready"):
    raise UpdateError("there is no verified vamOS update to activate")
  if state.get("active_slot") != active or target not in ("a", "b") or target == active:
    raise UpdateError("staged update does not target the inactive slot")

  state.update({"phase": "activating", "progress": 100})
  save_state(state)

  images = state.get("images")
  if not isinstance(images, dict):
    raise UpdateError("staged update has no image metadata")
  if not verify_installed():
    raise UpdateError("staged update failed its final on-device hash check")
  verify_system_contents(partition_path(target, "system"), str(state.get("version", "")))
  verify_esp_contents(partition_path(target, "esp"))

  try:
    boot_generation = prepare_trial_boot(active, target)
    state.update({
      "state": "ready",
      "phase": "ready",
      "progress": 100,
      "boot_generation": boot_generation,
      "ready_at": int(time.time()),
    })
    save_state(state, "trial-armed")
  except Exception as exc:
    rollback_error = None
    try:
      rollback_boot(active, target)
    except Exception as rollback_exc:
      rollback_error = str(rollback_exc)
    state["state"] = "failed"
    state["phase"] = "failed"
    state["error"] = str(exc)
    if rollback_error is not None:
      state["rollback_error"] = rollback_error
    save_state(state, "activation-failed")
    raise

  log(f"vamOS {state.get('version', 'unspecified')} is ready in slot {target}; next boot is a one-shot trial")
  if reboot:
    log("rebooting into trial slot")
    run(["reboot"], capture=False)
  return state


def install(manifest: Manifest, *, reboot: bool = False, activate: bool = True) -> dict:
  if os.geteuid() != 0:
    raise UpdateError("installation must run as root")
  if reboot and not activate:
    raise UpdateError("--reboot cannot be combined with --defer-activation")
  verify_layout()
  active = current_slot()
  target = "b" if active == "a" else "a"
  # Cancel a previous staged trial before touching either inactive partition.
  if selected_boot_control() is not None:
    rollback_boot(active, target)
  state = {
    "schema": 1,
    "state": "writing",
    "phase": "preparing",
    "progress": 0,
    "version": manifest.version,
    "manifest_source": manifest.source,
    "active_slot": active,
    "target_slot": target,
    "started_at": int(time.time()),
    "images": {image.name: asdict(image) for image in manifest.images},
  }
  save_state(state, "install-started")

  try:
    # Root first and ESP last keeps an interrupted target as far from bootable as possible.
    total_work = 2 * sum(image.size for image in manifest.images)
    completed_work = 0
    for name in ("system", "esp"):
      spec = next(image for image in manifest.images if image.name == name)
      work_before_image = completed_work

      def report_progress(phase: str, image_progress: int) -> None:
        phase_offset = 0 if phase == "writing" else spec.size
        current_work = work_before_image + phase_offset + spec.size * image_progress / 100
        state.update({
          "phase": phase,
          "image": spec.name,
          "image_progress": image_progress,
          "progress": min(98, int(current_work * 98 / total_work)),
        })
        save_state(state)

      write_image(spec, partition_path(target, name), progress_callback=report_progress)
      completed_work += 2 * spec.size

    state.update({"phase": "installing-selector", "progress": 98})
    save_state(state)
    state["boot_generation"] = prepare_disk_selector(active, target)
    state["esp_customized"] = True

    state.update({"phase": "validating", "progress": 99})
    state.pop("image", None)
    state.pop("image_progress", None)
    save_state(state)
    verify_system_contents(partition_path(target, "system"), manifest.version)
    verify_esp_contents(partition_path(target, "esp"))

    state.update({"state": "verified", "phase": "verified", "progress": 100})
    state["verified_at"] = int(time.time())
    save_state(state, "images-verified")
  except Exception as exc:
    rollback_error = None
    try:
      rollback_boot(active, target)
    except Exception as rollback_exc:
      rollback_error = str(rollback_exc)
    state["state"] = "failed"
    state["phase"] = "failed"
    state["error"] = str(exc)
    if rollback_error is not None:
      state["rollback_error"] = rollback_error
    save_state(state, "install-failed")
    raise

  if activate:
    return activate_staged(reboot=reboot)
  log(f"vamOS {manifest.version} is verified in inactive slot {target}; activation is deferred")
  return state


def verify_installed() -> bool:
  state = load_state()
  target = state.get("target_slot")
  images = state.get("images")
  if target not in ("a", "b") or not isinstance(images, dict):
    raise UpdateError("there is no staged update to verify")
  for name in ("system", "esp"):
    raw = images.get(name)
    if not isinstance(raw, dict):
      raise UpdateError(f"state has no {name} image")
    if name == "esp" and state.get("esp_customized"):
      verify_esp_contents(partition_path(target, name))
      log("esp: valid (slot label and boot control customized)")
    else:
      expected = str(raw["sha256"])
      size = int(raw["size"])
      actual = sha256_file(partition_path(target, name), size)
      if actual != expected:
        log(f"{name}: invalid ({actual}, expected {expected})")
        return False
      log(f"{name}: valid")
  return True


def status() -> dict:
  result: dict = {"state": load_state()}
  with contextlib.suppress(Exception):
    result["active_slot"] = current_slot()
  with contextlib.suppress(Exception):
    result["cmdline"] = cmdline()
  with contextlib.suppress(Exception):
    result["boot_control"] = selected_boot_control()
  result["layout"] = {}
  partitions = {
    "esp_a": disk_partition(1),
    "rootfs_a": disk_partition(2),
    "esp_b": disk_partition(3),
    "rootfs_b": disk_partition(4),
    "userdata": disk_partition(5),
  }
  for label, path in partitions.items():
    result["layout"][label] = {
      "path": str(path) if path.exists() else None,
      "size": block_size(path) if path.exists() else None,
    }
  return result


def _layout_json() -> dict:
  output = run(["sfdisk", "--json", str(DISK)]).stdout
  json_start = output.find("{")
  if json_start < 0:
    raise UpdateError("sfdisk did not return a JSON partition table")
  return json.loads(output[json_start:])["partitiontable"]


def _logical_sector_count(device: Path) -> int:
  size_bytes = int(run(["blockdev", "--getsize64", str(device)]).stdout.strip())
  sector_size = int(run(["blockdev", "--getss", str(device)]).stdout.strip())
  if sector_size <= 0 or size_bytes <= 0 or size_bytes % sector_size:
    raise UpdateError(f"invalid geometry for {device}: {size_bytes} bytes, {sector_size}-byte sectors")
  return size_bytes // sector_size


def _relocate_backup_gpt(table: dict) -> dict:
  device_sectors = _logical_sector_count(DISK)
  # GPT keeps one header plus its partition-entry array at each end.  The
  # reserved span is 34 sectors on 512-byte media and 6 sectors on 4096-byte
  # media; firstlba describes that span without assuming a sector size.
  first_lba = int(table["firstlba"])
  if first_lba <= 1 or first_lba >= device_sectors:
    raise UpdateError("GPT has an invalid first usable LBA")
  expected_last_lba = device_sectors - first_lba
  current_last_lba = int(table["lastlba"])
  if current_last_lba > expected_last_lba:
    raise UpdateError("GPT usable range exceeds the physical disk")
  if current_last_lba == expected_last_lba:
    return table

  log("moving the compact-image backup GPT to the end of the physical disk")
  run(["sfdisk", "--no-reread", "--relocate", "gpt-bak-std", str(DISK)], capture=False)
  run(["blockdev", "--rereadpt", str(DISK)], check=False, capture=False)
  relocated = _layout_json()
  if int(relocated["lastlba"]) != expected_last_lba:
    raise UpdateError("backup GPT relocation did not expose the full disk")
  return relocated


def expand_userdata() -> bool:
  """Grow the factory userdata partition and filesystem to fill larger media."""
  if os.geteuid() != 0:
    raise UpdateError("userdata expansion must run as root")

  table = _layout_json()
  partitions = table.get("partitions", [])
  labels = [partition.get("name") for partition in partitions]
  expected = ["esp_a", "rootfs_a", "esp_b", "rootfs_b", "userdata"]
  if labels[:5] != expected or len(partitions) != 5:
    log(f"userdata expansion skipped for partition layout: {labels}")
    return False

  table = _relocate_backup_gpt(table)
  partitions = table["partitions"]
  userdata = partitions[4]
  start = int(userdata["start"])
  current_size = int(userdata["size"])
  expanded_size = int(table["lastlba"]) - start + 1
  if expanded_size < current_size:
    raise UpdateError("userdata partition exceeds the physical disk")
  if expanded_size == current_size:
    # A previous boot may have committed the partition-table change but been
    # unable to observe the new block-device size before resize2fs.  The table
    # backup is retained until the filesystem grow completes, so use it as an
    # idempotent resume marker.
    if EXPAND_BACKUP.exists():
      device = disk_partition(5)
      if not device.exists():
        raise UpdateError(f"{device} is missing while resuming userdata expansion")
      log("finishing interrupted userdata filesystem expansion")
      run(["resize2fs", str(device)], capture=False)
      EXPAND_BACKUP.unlink(missing_ok=True)
      return True
    return False

  backup = EXPAND_BACKUP
  backup.write_text(run(["sfdisk", "--dump", str(DISK)]).stdout, encoding="utf-8")
  line = _sfdisk_partition_line(5, {**userdata, "size": expanded_size}, "userdata") + "\n"
  log(f"growing userdata from {current_size} to {expanded_size} sectors")
  completed = subprocess.run(
    ["sfdisk", "--no-reread", "--force", "-N", "5", str(DISK)],
    input=line,
    text=True,
  )
  if completed.returncode != 0:
    raise UpdateError(f"sfdisk failed while growing userdata; previous table is in {backup}")
  run(["partx", "-u", "--nr", "5", str(DISK)], check=False, capture=False)
  run(["udevadm", "settle", "--timeout=10"], check=False)

  device = disk_partition(5)
  for _ in range(50):
    if device.exists():
      break
    time.sleep(0.1)
  if not device.exists():
    raise UpdateError(f"{device} did not appear after growing userdata")
  actual_sectors = 0
  for _ in range(50):
    actual_sectors = _logical_sector_count(device)
    if actual_sectors == expanded_size:
      break
    time.sleep(0.1)
  if actual_sectors != expanded_size:
    raise UpdateError(f"kernel reports {actual_sectors} userdata sectors, expected {expanded_size}")
  run(["resize2fs", str(device)], capture=False)
  backup.unlink(missing_ok=True)
  log("userdata now uses the remaining physical storage")
  return True


def _rsync_userdata(source: Path, destination: Path) -> None:
  completed = run([
    "rsync", "-aHAXx", "--numeric-ids", "--exclude=.tmp_value_*",
    f"{source}/", f"{destination}/",
  ], check=False, capture=False)
  if completed.returncode == 24:
    log("userdata changed while it was copied; continuing after rsync warning 24")
  elif completed.returncode != 0:
    raise UpdateError(f"userdata rsync failed with status {completed.returncode}")


def _migrate_userdata(userdata_device: Path) -> None:
  if os.path.ismount("/data"):
    # A reboot after partition creation mounts the partial userdata volume at
    # /data. Bind-mounting / exposes the legacy rootfs /data below that mount.
    with tempfile.TemporaryDirectory(prefix="vamos-legacy-root-") as legacy_root:
      run(["mount", "--bind", "/", legacy_root], capture=False)
      try:
        _rsync_userdata(Path(legacy_root) / "data", Path("/data"))
        USERDATA_MARKER.touch()
        os.sync()
      finally:
        run(["umount", legacy_root], capture=False)
    return

  with tempfile.TemporaryDirectory(prefix="vamos-data-") as mount_dir:
    run(["mount", str(userdata_device), mount_dir], capture=False)
    try:
      destination = Path(mount_dir)
      _rsync_userdata(Path("/data"), destination)
      (destination / USERDATA_MARKER.name).touch()
      os.sync()
    finally:
      run(["umount", mount_dir], capture=False)


def _finish_layout_initialization() -> None:
  active = current_slot()
  selector = BOOT_SELECTOR_SOURCE.read_bytes()
  control = encode_boot_control({
    "generation": 1,
    "active": active,
    "pending": "",
    "phase": "stable",
    "root_a": root_reference("a"),
    "root_b": root_reference("b"),
  })
  for slot in ("a", "b"):
    try:
      _install_selector_on_slot(slot, selector, control)
    except (UpdateError, OSError, subprocess.SubprocessError):
      if slot == active:
        raise
  generation = set_boot_control(active)
  if os.path.ismount("/data"):
    LAYOUT_READY_MARKER.touch()
    os.sync()
  else:
    with tempfile.TemporaryDirectory(prefix="vamos-data-ready-") as mount_dir:
      run(["mount", str(disk_partition(5)), mount_dir], capture=False)
      try:
        (Path(mount_dir) / LAYOUT_READY_MARKER.name).touch()
        os.sync()
      finally:
        run(["umount", mount_dir], capture=False)
  log(f"A/B partitions and persistent userdata are ready in slot {active} (boot generation {generation})")


def _ensure_incomplete_layout_filesystems() -> None:
  filesystems = (
    (disk_partition(3), "vfat", ["mkfs.vfat", "-F", "32", "-n", "VAMOS-B"]),
    (disk_partition(4), "ext4", ["mkfs.ext4", "-F", "-L", "VAMOS-B"]),
    (disk_partition(5), "ext4", ["mkfs.ext4", "-F", "-L", "VAMOS-DATA"]),
  )
  for device, expected_type, format_command in filesystems:
    result = run(["blkid", "-s", "TYPE", "-o", "value", str(device)], check=False)
    actual_type = result.stdout.strip()
    if actual_type == expected_type:
      continue
    if actual_type:
      raise UpdateError(f"refusing to replace unexpected {actual_type} filesystem on {device}")
    log(f"finishing interrupted {expected_type} filesystem creation on {device}")
    run([*format_command, str(device)], capture=False)


def initialize_layout(*, confirm: bool) -> None:
  if os.geteuid() != 0:
    raise UpdateError("layout initialization must run as root")
  if not confirm:
    raise UpdateError("layout initialization requires --yes")

  table = _layout_json()
  partitions = table.get("partitions", [])
  labels = [partition.get("name") for partition in partitions]
  if labels[:5] == ["esp_a", "rootfs_a", "esp_b", "rootfs_b", "userdata"]:
    if USERDATA_MARKER.exists():
      _finish_layout_initialization()
      return
    log("resuming incomplete A/B userdata migration")
    _ensure_incomplete_layout_filesystems()
    _migrate_userdata(disk_partition(5))
    _finish_layout_initialization()
    return
  if len(partitions) != 2 or labels not in (["esp", "rootfs"], ["esp_a", "rootfs_a"]):
    raise UpdateError(f"refusing to migrate unexpected partition layout: {labels}")

  table = _relocate_backup_gpt(table)
  partitions = table["partitions"]

  sector_size = int(table["sectorsize"])
  if sector_size != 512:
    raise UpdateError(f"unsupported sector size {sector_size}")
  esp_sectors = ESP_SIZE // sector_size
  system_sectors = SYSTEM_SIZE // sector_size
  p1, p2 = partitions
  if int(p1["size"]) != esp_sectors or int(p2["size"]) != system_sectors:
    raise UpdateError("legacy ESP/rootfs sizes do not match the vamOS layout")

  next_sector = int(p2["start"]) + int(p2["size"])
  p3_start = next_sector
  p4_start = p3_start + esp_sectors
  p5_start = p4_start + system_sectors
  last_lba = int(table["lastlba"])
  if p5_start + 2 * 1024 * 1024 // sector_size >= last_lba:
    raise UpdateError("disk is too small for two vamOS slots and userdata")

  backup_dir = STATE_DIR
  backup_dir.mkdir(parents=True, exist_ok=True)
  backup = backup_dir / f"partition-table-before-ab-{int(time.time())}.sfdisk"
  backup.write_text(run(["sfdisk", "--dump", str(DISK)]).stdout, encoding="utf-8")
  log(f"saved partition-table backup to {backup}")

  # Install the fixed selector before changing GPT labels. Its immutable root
  # PARTUUID remains valid on either side of the migration.
  migration_control = encode_boot_control({
    "generation": 1,
    "active": "a",
    "pending": "",
    "phase": "stable",
    "root_a": f"PARTUUID={p2['uuid']}",
    "root_b": "PARTLABEL=rootfs_b",
  })
  _install_selector_on_slot("a", BOOT_SELECTOR_SOURCE.read_bytes(), migration_control, device=disk_partition(1))

  lines = [
    "label: gpt",
    f"label-id: {table['id']}",
    f"device: {DISK}",
    "unit: sectors",
    f"first-lba: {table['firstlba']}",
    f"last-lba: {table['lastlba']}",
    f"sector-size: {sector_size}",
    "",
    _sfdisk_partition_line(1, p1, "esp_a"),
    _sfdisk_partition_line(2, p2, "rootfs_a"),
    f"{disk_partition(3)} : start={p3_start}, size={esp_sectors}, type=C12A7328-F81F-11D2-BA4B-00A0C93EC93B, name=\"esp_b\"",
    f"{disk_partition(4)} : start={p4_start}, size={system_sectors}, type=0FC63DAF-8483-4772-8E79-3D69D8477DE4, name=\"rootfs_b\"",
    f"{disk_partition(5)} : start={p5_start}, size={last_lba - p5_start + 1}, type=0FC63DAF-8483-4772-8E79-3D69D8477DE4, name=\"userdata\"",
    "",
  ]
  layout = "\n".join(lines)
  completed = subprocess.run(["sfdisk", "--no-reread", "--force", str(DISK)], input=layout, text=True)
  if completed.returncode != 0:
    raise UpdateError("sfdisk failed while creating the A/B layout")
  run(["partx", "-u", str(DISK)], check=False, capture=False)
  run(["partx", "-a", "--nr", "3:5", str(DISK)], check=False, capture=False)
  run(["udevadm", "settle", "--timeout=10"], check=False)

  for number in (3, 4, 5):
    device = disk_partition(number)
    for _ in range(50):
      if device.exists():
        break
      time.sleep(0.1)
    if not device.exists():
      raise UpdateError(f"{device} did not appear; reboot into slot A and run initialize again")

  run(["mkfs.vfat", "-F", "32", "-n", "VAMOS-B", str(disk_partition(3))], capture=False)
  run(["mkfs.ext4", "-F", "-L", "VAMOS-B", str(disk_partition(4))], capture=False)
  run(["mkfs.ext4", "-F", "-L", "VAMOS-DATA", str(disk_partition(5))], capture=False)

  _migrate_userdata(disk_partition(5))
  _finish_layout_initialization()


def _sfdisk_partition_line(number: int, partition: dict, name: str) -> str:
  fields = [
    f"start={partition['start']}",
    f"size={partition['size']}",
    f"type={partition['type']}",
  ]
  if partition.get("uuid"):
    fields.append(f"uuid={partition['uuid']}")
  fields.append(f"name=\"{name}\"")
  return f"{disk_partition(number)} : " + ", ".join(fields)


def main(argv: Sequence[str] | None = None) -> int:
  parser = argparse.ArgumentParser(description="Install and manage A/B vamOS updates")
  subparsers = parser.add_subparsers(dest="command", required=True)

  install_parser = subparsers.add_parser("install", help="install from a vamOS JSON manifest")
  install_parser.add_argument("manifest")
  install_parser.add_argument("--reboot", action="store_true")
  install_parser.add_argument("--defer-activation", action="store_true")

  local_parser = subparsers.add_parser("local", help="install a directory containing esp.img and system.img")
  local_parser.add_argument("directory", type=Path)
  local_parser.add_argument("--reboot", action="store_true")

  activate_parser = subparsers.add_parser("activate", help="activate the verified inactive slot for a one-shot trial")
  activate_parser.add_argument("--reboot", action="store_true")

  subparsers.add_parser("verify", help="verify the currently staged images")
  subparsers.add_parser("status", help="show slots, boot-control state, and update state")

  edl_parser = subparsers.add_parser("request-edl", help="request one-shot EDL through U-Boot")
  edl_parser.add_argument("--no-reboot", action="store_true")

  initialize_parser = subparsers.add_parser("initialize", help="migrate a legacy Dragon disk to A/B")
  initialize_parser.add_argument("--yes", action="store_true")
  subparsers.add_parser("expand", help="grow factory userdata to fill larger storage")

  args = parser.parse_args(argv)
  try:
    if args.command == "status":
      print(json.dumps(status(), indent=2, sort_keys=True))
      return 0
    with update_lock():
      if args.command == "install":
        install(load_manifest(args.manifest), reboot=args.reboot, activate=not args.defer_activation)
      elif args.command == "local":
        install(manifest_from_directory(args.directory), reboot=args.reboot)
      elif args.command == "activate":
        activate_staged(reboot=args.reboot)
      elif args.command == "verify":
        return 0 if verify_installed() else 1
      elif args.command == "request-edl":
        request_edl(reboot=not args.no_reboot)
      elif args.command == "initialize":
        initialize_layout(confirm=args.yes)
      elif args.command == "expand":
        expand_userdata()
    return 0
  except (UpdateError, OSError, urllib.error.URLError, json.JSONDecodeError, lzma.LZMAError) as exc:
    print(f"vamos-update: ERROR: {exc}", file=sys.stderr)
    return 1


if __name__ == "__main__":
  raise SystemExit(main())
